import fullCode from './kruskal.py?raw';
import { highlightPython, copyCode } from '../kruskal/highlight';
export interface LessonStep { title: string; text: string; code: string; output?: string; task: string; answer: string; }
const edges = 'arestas = [(8, "A", "D"), (2, "B", "C"), (9, "B", "D"),\n           (1, "A", "B"), (4, "C", "D"), (3, "A", "C")]';
export const steps: LessonStep[] = [
  { title:'Primeira célula no Colab',text:'Abra um notebook em branco no Google Colab. Uma célula de código é um espaço para escrever Python. Digite o exemplo e pressione Shift + Enter para executar. Execute as próximas células na ordem. Não é preciso instalar nada. Uma variável guarda um valor; = guarda o valor da direita no nome da esquerda. print mostra um resultado. Textos ficam entre aspas.',code:'nome = "Nicolle"\nprint("Olá,", nome)',output:'Olá, Nicolle',task:'Troque o nome e execute de novo. O que muda?',answer:'Muda o texto mostrado. A variável nome passa a guardar o novo texto.' },
  { title:'Das ilhas para um grafo',text:'Um grafo descreve objetos e conexões. Cada ilha é um vértice, identificado por uma letra. Cada caminho é uma aresta, com um custo chamado peso. Um caminho A–B pode ser usado nos dois sentidos neste jogo. Queremos conectar todas as ilhas, mesmo passando por outras, com o menor custo total. Uma lista usa colchetes e guarda vários valores; len conta seus elementos.',code:'vertices = ["A", "B", "C", "D"]\nprint(vertices)\nprint("Quantidade de ilhas:", len(vertices))',output:"['A', 'B', 'C', 'D']\nQuantidade de ilhas: 4",task:'Quantos caminhos terá uma árvore conectando quatro ilhas?',answer:'Três. Uma árvore é uma rede conectada sem ciclos. Com n vértices, ela tem n − 1 arestas. Um ciclo acontece quando há um caminho fechado, como A–B–C–A.' },
  { title:'Guardar os caminhos e seus custos',text:'Cada tupla, escrita com parênteses, descreve uma aresta: (custo, ilha de origem, ilha de destino). A lista abaixo é exatamente o mapa de quatro ilhas do jogo. Os números são custos de construção, não distâncias na tela. O custo vem primeiro para facilitar a ordenação. O índice 0 acessa o primeiro item de uma lista.',code:edges+'\nprint(arestas[0])',output:"(8, 'A', 'D')",task:'Qual caminho a primeira tupla representa?',answer:'A–D, com custo 8. A posição na lista ainda não significa a ordem em que Kruskal escolherá os caminhos.' },
  { title:'Ler uma aresta e percorrer uma lista',text:'custo, a, b = aresta separa os três valores de uma tupla em três variáveis. for repete as linhas recuadas uma vez para cada item da lista. Os dois-pontos iniciam o bloco; use quatro espaços nas linhas dentro dele. Cada repetição atualiza custo, a e b.',code:'for custo, a, b in arestas:\n    print(a, "até", b, "custa", custo)',output:'A até D custa 8\nB até C custa 2\nB até D custa 9\nA até B custa 1\nC até D custa 4\nA até C custa 3',task:'O que aconteceria se print não estivesse recuado?',answer:'Sem nenhuma instrução recuada após for, Python dá um erro de indentação. O recuo faz parte da estrutura do programa.' },
  { title:'Ordenar do menor para o maior',text:'sorted cria uma nova lista ordenada. Como o custo está na primeira posição das tuplas, ele é comparado primeiro. Em empates, Python compara as letras. Qualquer ordem entre arestas de mesmo custo funciona para Kruskal, embora a árvore escolhida possa mudar.',code:'ordenadas = sorted(arestas)\nfor custo, a, b in ordenadas:\n    print(custo, a, b)',output:'1 A B\n2 B C\n3 A C\n4 C D\n8 A D\n9 B D',task:'Kruskal deve aceitar automaticamente todas as arestas mais baratas?',answer:'Não. A aresta A–C custa 3, mas depois de A–B e B–C ela fecharia um ciclo. Também precisamos verificar os grupos.' },
  { title:'Um grupo para cada ilha',text:'Um dicionário guarda pares de chave e valor. Aqui, grupo["B"] informa o rótulo do grupo de B. {} cria um dicionário vazio. No início, cada ilha está sozinha, então o rótulo é a própria letra. Ilhas com o mesmo rótulo já estão conectadas. O nome do rótulo não importa; a igualdade entre os rótulos importa.',code:'grupo = {}\nfor vertice in vertices:\n    grupo[vertice] = vertice\nprint(grupo)\nprint("Grupo de B:", grupo["B"])',output:"{'A': 'A', 'B': 'B', 'C': 'C', 'D': 'D'}\nGrupo de B: B",task:'Antes de construir qualquer caminho, quantos grupos existem?',answer:'Quatro. Cada ilha está em seu próprio grupo.' },
  { title:'Aceitar A–B e unir os grupos',text:'if executa o bloco apenas quando a condição é verdadeira. != significa diferente; == compara se dois valores são iguais. Como A e B estão em grupos diferentes, podemos conectá-los. Guardamos os dois rótulos antes da união. Depois percorremos todas as ilhas: quem pertencia ao grupo de B recebe o rótulo do grupo de A. Copie também a reinicialização; ela permite executar esta célula novamente sem depender de mudanças anteriores.',code:'grupo = {}\nfor vertice in vertices:\n    grupo[vertice] = vertice\n\ncusto, a, b = ordenadas[0]\ngrupo_a = grupo[a]\ngrupo_b = grupo[b]\n\nif grupo_a != grupo_b:\n    for vertice in vertices:\n        if grupo[vertice] == grupo_b:\n            grupo[vertice] = grupo_a\n\nprint(grupo)',output:"{'A': 'A', 'B': 'A', 'C': 'C', 'D': 'D'}",task:'Depois de aceitar B–C, por que A–C deve ser rejeitado?',answer:'B já tem o rótulo A. Unir B–C também dá esse rótulo a C. A e C ficam no mesmo grupo: já há a ligação A–B–C. Adicionar A–C fecha um ciclo.' },
  { title:'Repetir a decisão: Kruskal completo',text:'Agora combinamos os passos. arvore é uma lista dos caminhos aceitos; append adiciona um item ao final. custo_total começa em zero e soma só os caminhos aceitos. else mostra os caminhos rejeitados. break encerra o laço quando temos n − 1 caminhos: neste mapa conectado, a árvore está pronta. Os recuos mostram qual instrução pertence a qual bloco.',code:'grupo = {}\nfor vertice in vertices:\n    grupo[vertice] = vertice\n\narvore = []\ncusto_total = 0\n\nfor custo, a, b in sorted(arestas):\n    grupo_a = grupo[a]\n    grupo_b = grupo[b]\n    if grupo_a != grupo_b:\n        for vertice in vertices:\n            if grupo[vertice] == grupo_b:\n                grupo[vertice] = grupo_a\n        arvore.append((custo, a, b))\n        custo_total = custo_total + custo\n        print("Aceitar", a, b, custo)\n        if len(arvore) == len(vertices) - 1:\n            break\n    else:\n        print("Rejeitar", a, b, "ciclo")\n\nprint("Custo total:", custo_total)',output:'Aceitar A B 1\nAceitar B C 2\nRejeitar A C ciclo\nAceitar C D 4\nCusto total: 7',task:'Por que os caminhos de custos 8 e 9 não aparecem na saída?',answer:'Após aceitar C–D, temos três caminhos para quatro ilhas, todas conectadas. break encerra o laço antes de examinar as arestas restantes.' },
  { title:'Transformar em uma função reutilizável',text:'def define uma função: um bloco que pode ser chamado usando um nome. vertices e arestas são os dados recebidos em cada chamada. As variáveis criadas dentro da função pertencem àquela execução. return entrega os resultados e termina a função. A atribuição arvore, custo_total = kruskal(...) separa os dois resultados. Digite esta versão em uma nova célula; compare seus blocos com a etapa anterior.',code:fullCode,output:"Caminhos: [(1, 'A', 'B'), (2, 'B', 'C'), (4, 'C', 'D')]\nCusto total: 7",task:'Explique com suas palavras a linha if grupo_a != grupo_b.',answer:'Ela verifica se as pontas da aresta ainda pertencem a grupos diferentes. Se sim, a aresta conecta duas partes separadas sem criar um ciclo, então pode entrar na árvore.' },
  { title:'Testar e explicar sem decorar',text:'assert verifica uma condição. Se for verdadeira, não mostra nada; se for falsa, interrompe com AssertionError. Agora vamos alterar um custo. Escreva sua previsão antes de executar. A função não modifica a lista de entrada e pode ser usada de novo com outro mapa.',code:'novas_arestas = [(8, "A", "D"), (2, "B", "C"), (9, "B", "D"),\n                 (1, "A", "B"), (10, "C", "D"), (3, "A", "C")]\nnova_arvore, novo_custo = kruskal(vertices, novas_arestas)\nprint(nova_arvore)\nprint(novo_custo)\nassert novo_custo == 11\nassert len(nova_arvore) == 3',output:"[(1, 'A', 'B'), (2, 'B', 'C'), (8, 'A', 'D')]\n11",task:'Na apresentação, explique: por que ordenar? Por que rejeitar um ciclo? Por que atualizar todas as ilhas do grupo antigo?',answer:'Ordenamos para considerar primeiro as conexões mais baratas. Uma aresta dentro do mesmo grupo não conecta nenhuma parte nova e cria um ciclo. Atualizamos todos os membros para continuar reconhecendo corretamente quem já está conectado.' },
];
const escape=(s:string):string=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function lessonPage(): string {
  return `<main class="page lesson-page"><a class="back-link" href="#/grafos/evento/jogo-kruskal">← Voltar ao jogo</a><div class="page-heading"><p class="eyebrow">Do primeiro print ao algoritmo do jogo</p><h1 id="view-title" tabindex="-1">Kruskal, uma célula por vez</h1><p class="subtitle">Para Nicolle acompanhar no Colab, escrever o próprio código e explicar cada decisão.</p></div><section class="lesson-panel glass" data-glass><h2>Seu caderno de estudo</h2><p>Leia, digite, execute e compare a saída. Os exemplos usam sempre o mesmo mapa de quatro ilhas. Se aparecer um erro, confira aspas, nomes das variáveis e espaços no começo das linhas. Se reiniciar a sessão do Colab, execute as células novamente desde o início.</p><p><a href="https://colab.research.google.com/" target="_blank" rel="noopener">Abrir Google Colab ↗</a> · <button data-notebook>Baixar caderno para preencher ↓</button> · <a href="${import.meta.env.BASE_URL}grafos/kruskal.py" download>Referência completa .py ↓</a></p><p>O caderno contém as instruções e células vazias, para você construir a solução. Não exige bibliotecas extras.</p><p id="lesson-progress" role="status"></p><nav class="lesson-index" aria-label="Etapas">${steps.map((s,i)=>`<a href="#lesson-step-${i+1}" data-step-link="${i+1}">${i+1}. ${s.title}</a>`).join('')}</nav></section>
    ${steps.map((s,i)=>`<section class="lesson-panel glass" data-glass id="lesson-step-${i+1}"><div class="lesson-step-heading"><p class="eyebrow">Etapa ${i+1} de ${steps.length}</p><label><input type="checkbox" data-done="${i}"/> Concluí</label></div><h2>${s.title}</h2><p>${s.text}</p><div class="code-caption"><span>Digite em uma célula Python</span><button data-copy="${i}">Copiar exemplo</button></div><pre class="python-code"><code>${highlightPython(s.code)}</code></pre>${s.output?`<p class="output-label">Saída esperada</p><pre class="expected-output"><samp>${escape(s.output)}</samp></pre>`:''}<p><strong>Sua vez:</strong> ${s.task}</p><details><summary>Conferir o raciocínio</summary><p>${s.answer}</p></details></section>`).join('')}
    <section class="lesson-panel glass" data-glass><h2>Por que isso encontra o menor custo?</h2><p>Em cada etapa, Kruskal escolhe a aresta mais barata disponível que liga dois grupos diferentes. É seguro uni-los: se outra árvore usa uma conexão mais cara entre essas partes, podemos trocá-la por esta sem aumentar o custo. Repetindo essas escolhas e evitando ciclos, chegamos a uma árvore de custo mínimo.</p><p>Todos os mapas do jogo são conectados. Se não houver caminho possível entre algumas ilhas, o algoritmo termina com grupos separados: não existe árvore que conecte todas. Ele produz uma floresta, uma árvore por componente.</p><p>Nosso dicionário representa conjuntos disjuntos usando rótulos simples. Percorrer todas as ilhas torna a união fácil de entender. Implementações com Union-Find fazem essa parte mais rapidamente; a regra de Kruskal continua a mesma.</p><h2>Checklist para a apresentação</h2><ul><li>Mostrar vértices, arestas e pesos no jogo.</li><li>Explicar a lista de tuplas e a ordenação.</li><li>Demonstrar a união de A–B e B–C.</li><li>Explicar por que A–C fecha um ciclo.</li><li>Chegar a três caminhos, custo 7, e comparar com a trapaça.</li></ul><p><a href="#/grafos/evento/jogo-kruskal">Praticar no jogo →</a></p><p class="footnote">Referências: <a href="${import.meta.env.BASE_URL}grafos/agm.pdf">slides da disciplina</a>, <a href="https://docs.python.org/3/tutorial/datastructures.html" target="_blank" rel="noopener">estruturas de dados em Python</a> e <a href="https://docs.python.org/3/tutorial/controlflow.html" target="_blank" rel="noopener">controle de fluxo em Python</a>. Cores do código: 12 cores ANSI cromáticas mapeadas com mapColors, da nicrainha.</p></section></main>`;
}
export function mountLesson(root:HTMLElement):()=>void {
  const key='nicolle-kruskal-lesson-v1';let done:number[]=[];
  try { const stored=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(stored))done=stored.filter(n=>Number.isInteger(n)&&n>=0&&n<steps.length); } catch { /* Progress is optional. */ }
  function progress():void { root.querySelector('#lesson-progress')!.textContent=`${new Set(done).size} de ${steps.length} etapas concluídas neste navegador.`;root.querySelectorAll<HTMLInputElement>('[data-done]').forEach(input=>input.checked=done.includes(Number(input.dataset.done))); }
  progress();
  const change=(event:Event):void=>{const input=event.target as HTMLInputElement;if(input.dataset.done===undefined)return;const index=Number(input.dataset.done);done=done.filter(n=>n!==index);if(input.checked)done.push(index);try{localStorage.setItem(key,JSON.stringify(done));}catch{}progress();};
  const click=async(event:Event):Promise<void>=>{
    const target=(event.target as HTMLElement).closest<HTMLElement>('[data-copy],[data-notebook],[data-step-link]');if(!target)return;
    if(target.dataset.stepLink){event.preventDefault();root.querySelector(`#lesson-step-${target.dataset.stepLink}`)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
    if(target.dataset.copy!==undefined){const ok=await copyCode(steps[Number(target.dataset.copy)].code);target.textContent=ok?'Copiado!':'Selecione o código para copiar';}
    if(target.hasAttribute('data-notebook')){
      const notebook={nbformat:4,nbformat_minor:5,metadata:{kernelspec:{display_name:'Python 3',language:'python',name:'python3'},language_info:{name:'python'}},cells:steps.flatMap((s,i)=>[{cell_type:'markdown',id:`texto-${i}`,metadata:{},source:[`## ${i+1}. ${s.title}\n\n${s.text}\n\n**Sua vez:** ${s.task}\n\nAcompanhe os exemplos na página da aula. Digite seu código na célula abaixo.\n${s.output?'\nSaída esperada:\n```text\n'+s.output+'\n```':''}`]},{cell_type:'code',id:`codigo-${i}`,metadata:{},execution_count:null,outputs:[],source:[]}])};
      const url=URL.createObjectURL(new Blob([JSON.stringify(notebook,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='nicolle-kruskal-caderno.ipynb';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
    }
  };
  root.addEventListener('change',change);root.addEventListener('click',click);
  return()=>{root.removeEventListener('change',change);root.removeEventListener('click',click);};
}
